export const ADD_PRODUCT: "ADD_PRODUCT" = "ADD_PRODUCT";
export const REMOVE_PRODUCT: "REMOVE_PRODUCT" = "REMOVE_PRODUCT";
export const REORDER_PRODUCTS: "REORDER_PRODUCTS" = "REORDER_PRODUCTS";
export const RESET: "RESET" = "RESET";
