export const ORDER_REQUEST: "ORDER_REQUEST" = "ORDER_REQUEST";
export const ORDER_FAILED: "ORDER_FAILED" = "ORDER_FAILED";
export const ORDER_SUCCESS: "ORDER_SUCCESS" = "ORDER_SUCCESS";
export const ORDER_RESET: "ORDER_RESET" = "ORDER_RESET";
export const ORDER_ADD_DETAILS: "ORDER_ADD_DETAILS" = "ORDER_ADD_DETAILS";
export const ORDER_HISTORY_REQUEST: "ORDER_HISTORY_REQUEST" =
  "ORDER_HISTORY_REQUEST";
export const ORDER_HISTORY_SUCCESS: "ORDER_HISTORY_SUCCESS" =
  "ORDER_HISTORY_SUCCESS";
