export const EDIT_REQUEST: "EDIT_REQUEST" = "EDIT_REQUEST";
export const EDIT_SUCCESS: "EDIT_SUCCESS" = "EDIT_SUCCESS";
export const EDIT_FAILED: "EDIT_FAILED" = "EDIT_FAILED";

export const RESET_REQUEST: "RESET_REQUEST" = "RESET_REQUEST";
export const RESET_REQUEST_FAILED: "RESET_REQUEST_FAILED" =
  "RESET_REQUEST_FAILED";

export const RESET_SUCCESS: "RESET_SUCCESS" = "RESET_SUCCESS";
export const RESET_FAILED: "RESET_FAILED" = "RESET_FAILED";
export const RESETED: "RESETED" = "RESETED" 

export const TOKEN_UPDATE: "TOKEN_UPDATE" = "TOKEN_UPDATE";
export const TOKEN_UPDATE_FAILED: "TOKEN_UPDATE_FAILED" = "TOKEN_UPDATE_FAILED";

export const AUTH_CHECKED: "AUTH_CHECKED" = "AUTH_CHECKED";
export const AUTH_FAILED: "AUTH_FAILED" = "AUTH_FAILED";

export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";
